# Linter Options
options:
    merge-default-rules: true

# Rule Configuration
rules:
    force-attribute-nesting: 0
    force-pseudo-nesting: 0
    quotes: 2
    indentation:
        - 2
        - size: 4
    nesting-depth:
        - 1
        - max-depth: 5
